# theme: jekyll-theme-cayman
# Exclude files from Jekyll build
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
exclude:
    - README.md
    - LICENSE
    - CNAME
    - Gemfile
    - Gemfile.lock
    - vendor

# Installed gems
plugins:
  - jekyll-include-cache
  - jekyll-target-blank
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

 

# Gem settings


# Site Author
author:
  name             : "Evelyn J Boettcher"
  avatar           : "/assets/img/index/evelyn_boettcher_2022_3_4.png"
  bio              : "Physicist and Founder"
  location         : "Dayton"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.didactex.com"
    - label: "GitHub"
      icon: "fas fa-code-branch"
      url: "https://github.com/ejboettcher"
    - label: "Instructables"
      icon: "fas fa-file"
      url: "https://www.instructables.com/member/Gem+City+Sewn/"


# Site settings
encoding: utf-8
locale          : "en-US"
lang            : en-US
title           : "Evelyn J. Boettcher"
title_separator : "-"
subtitle        : "CV"
tesser          : "/assets/img/logos/dayton_gearfilled@128px.png"
logo            : "/assets/img/logos/dayton_gearfilled@128px.png"
description: "Evelyn J. Boettcher CV"
#baseurl: "/evelyn_j_boettcher_cv"
#url: "https://ejboettcher.github.io"
baseurl: "/"
url: "http://www.evelyn.boettcher.com"
repo: "/evelyn_j_boettcher_cv"
repository: "evelyn_j_boettcher_cv/ejboettcher.github.io"
email: "evelyn.boettcher@gmail.com"
header:
  overlay_image: "/assets/img/banner/green_painting.png"
  caption: "Evelyn J. Boettcher"
  image_description: "Green painting banner Image"
#google_analytics: UA-92956541-1
css_inline: false 
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true 

# Favicons 
favicons: 
    16: '/assets/img/logos/dayton_gearfilled@16px.png'
    32: '/assets/img/logos/dayton_gearfilled@32px.png'
    64: '/assets/img/logos/dayton_gearfilled@64px.png'
    128: '/assets/img/logos/dayton_gearfilled@128px.png'
    256: '/assets/img/logos/dayton_gearfilled@256px.png'
    512: '/assets/img/logos/dayton_gearfilled@512px.png'
    1024: '/assets/img/logos/dayton_gearfilled@1024px.png'

# Site navigation
navigation_header:
- title: Home
  url: /
- title: Tutorials
  url: /tutorials.html
- title: Publications
  url: /publications.html
- title: Contact
  url: /contact.html


# Define collections

# Analytics
analytics:
  provider    : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id : "G-LQ3LRHD7NK"
    anonymize_ip: false 
    
    
# Collections
collections:
  tutorials:
    output: true
    permalink: /tutorials/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _tutorials
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      related: true

    
# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ejboettcher"



# Liquid
strict_front_matter: true
liquid:
  error_mode: strict
