# theme: jekyll-theme-cayman
# Exclude files from Jekyll build
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin    : "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
exclude:
    - README.md
    - LICENSE
    - CNAME
    - Gemfile
    - Gemfile.lock
    - vendor

# Installed gems
plugins:
  - jekyll-include-cache
  #  - jekyll-target-blank
  #  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Gem settings

# Site settings
encoding: utf-8
locale                   : "en-US"
lang: en-US
title: "Evelyn J. Boettcher"
title_separator          : "-"
subtitle                 : "CV"
tesser: "/assets/img/logos/dayton_gearfilled@128px.png"
logo                     : "/assets/img/logos/dayton_gearfilled@128px.png"
description: "Evelyn J. Boettcher CV"
# baseurl: "https://ejboettcher.github.io/evelyn_j_boettcher_cv"
baseurl: "/evelyn_j_boettcher_cv"
url: "https://ejboettcher.github.io"
repo: "ejboettcher/evelyn_j_boettcher_cv"
email: "evelyn.boettcher@gmail.com"
#google_analytics: UA-92956541-1
css_inline: false 
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true 

# Favicons 
favicons: 
    16: '/assets/img/logos/dayton_gearfilled@16px.png'
    32: '/assets/img/logos/dayton_gearfilled@32px.png'
    64: '/assets/img/logos/dayton_gearfilled@64px.png'
    128: '/assets/img/logos/dayton_gearfilled@128px.png'
    256: '/assets/img/logos/dayton_gearfilled@256px.png'
    512: '/assets/img/logos/dayton_gearfilled@512px.png'
    1024: '/assets/img/logos/dayton_gearfilled@1024px.png'

# Site navigation
navigation_header:
- title: Home
  url: /
- title: Tutorials
  url: /tutorials.html
- title: Contact
  url: /contact.html

# Define collections

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id  
    
    

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:path/


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _tutorials
  - scope:
      path: ""
      type: tutorials
    values:
      layout: single
      author_profile: false
      share: true
    
# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"


# Liquid
strict_front_matter: true
liquid:
  error_mode: strict
